language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ihaKhQY3QPaWq6lZ9kHg9QP2n/QHwby+rKeu3tJq9GYnp1fZpW64zloahZP6i+7z1+x4j9UdXBhRnO9pKlal/0nxlIPjt6kcfkVMPvK7qjVyvqjxEOxxoiB+pQePZwl3ppQQDtItHI366cUUFAQDJ3y8Da7k4JetKriLwrNeP1RsHCVqN7v0FKuNGe+t0dwWSfa4IewcPnYiNLZhDJl0EIkWFefCeBtgxMDlMr0/D1VzSSOMEWtpIUmepaEpe67qE8uUNhjnaMqY2gw9Wn/eB2JvM05chUYL6+II2Z/hft90IF7+FIY7xB6g1qKtyvu05QSEAkkDco02cQ/ENkIWtnghKcG8YVxsZBWjDz3ozWDOdqZ3bHrB47W6fUQsSw1ldSnqkIrZs6UetTNN3XeMesT3jhQfzaRcpa0nx+PmWy40P20VMp7HsTBOK17/WkmM0hg2ciqPaVYEl5SJxOcijqXM9F5tJjBGaH2yHQt0V9yC1IAmg90bxOqe7ayt0GA0mD5MWJYICuW7e9aXnsWqimQFeoNfuKCD4hd0rc+rcUKkvbK/OvC9mAZWRmPntS4ax4RGI0Mw1zJJLdgAK7d4UUQNUFpL8JrO8J6oqcbwWO3HyaPPhNndWSqgmAnyaqPTC8BF93Y0smxVXGe7cjbczGfUfxwIzf83s3ByRKR9qvY=
  app: spaced-repitetition-server
  on:
    repo: thinkful-ei26/spaced-repetition-jordan-taylor-server
